import { BaseModel } from "./BaseModel";

export class RubberFarmModel extends BaseModel {
  rubberFarmId: number;
  farmerId: number;
  villageName: string;
  moo: number;
  road: string;
  alley: string;
  subDistrict: string;
  district: string;
  province: string;
  location: any; // JSON for GeoJSON data
  productDistributionType: string;
  plantingDetails: any[]; // Optional array of planting details
  version?: number; // Optimistic locking

  constructor(
    rubberFarmId: number,
    farmerId: number,
    villageName: string,
    moo: number,
    road: string,
    alley: string,
    subDistrict: string,
    district: string,
    province: string,
    location: any,
    productDistributionType: string,
    plantingDetails: any[] = [],
    createdAt: Date = new Date(),
    updatedAt: Date = new Date(),
    version?: number
  ) {
    super(rubberFarmId, createdAt, updatedAt);
    this.rubberFarmId = rubberFarmId;
    this.farmerId = farmerId;
    this.villageName = villageName;
    this.moo = moo;
    this.road = road;
    this.alley = alley;
    this.subDistrict = subDistrict;
    this.district = district;
    this.province = province;
    this.location = location;
    this.productDistributionType = productDistributionType;
    this.plantingDetails = plantingDetails;
    this.version = version;
  }

  static create(
    farmerId: number,
    villageName: string,
    moo: number,
    road: string,
    alley: string,
    subDistrict: string,
    district: string,
    province: string,
    location: any,
    productDistributionType: string
  ): RubberFarmModel {
    return new RubberFarmModel(
      0, // rubberFarmId will be generated by the database
      farmerId,
      villageName,
      moo,
      road,
      alley,
      subDistrict,
      district,
      province,
      location,
      productDistributionType
    );
  }

  validate(): boolean {
    return (
      this.farmerId > 0 &&
      this.villageName.trim().length > 0 &&
      this.moo > 0 &&
      this.subDistrict.trim().length > 0 &&
      this.district.trim().length > 0 &&
      this.province.trim().length > 0 &&
      this.location !== null &&
      this.location !== undefined
    );
  }

  toJSON(): Record<string, any> {
    return {
      rubberFarmId: this.rubberFarmId,
      farmerId: this.farmerId,
      villageName: this.villageName,
      moo: this.moo,
      road: this.road,
      alley: this.alley,
      subDistrict: this.subDistrict,
      district: this.district,
      province: this.province,
      location: this.location,
      productDistributionType: this.productDistributionType,
      plantingDetails: this.plantingDetails,
      createdAt: this.createdAt,
      updatedAt: this.updatedAt,
      version: this.version,
    };
  }
}
